### ISSUE TITLE
Help: There is a problem with the directory

### ISSUE THREAD

**Issue by monkeycc** [MlLearnerAkash/imgAugForLabelmeAnootation#1]
thanks

This is a very practical tool

But I encountered a problem

```python
    img_files = sorted(glob.glob(r"E:\IMG"))
    json_files = sorted(glob.glob(r"E:\JSON"))

    
    for img_file, json_file in zip(sorted(img_files), sorted(json_files)):
        start_time = time.time()
        print("[Manna log: img_file]: ", img_file)
        print("[Manna log: json_file]: ", json_file)
        augmentation(img_file, json_file, my_augmenter, NUM_AUG, r"E:\OUT/")
        end_time = time.time()
        print("Elapsed time: {:.2f} seconds".format(end_time - start_time))
        print("\n\n")

```

```python
[Manna log: img_file]:  E:\IMG
[Manna log: json_file]:  E:\JSON
[ WARN:0@0.661] global loadsave.cpp:244 cv::findDecoder imread_('E:\IMG'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "e:/2023_Code_WEB/imgAugForLabelmeAnootation-main/poly_aug.py", line 166, in <module>
    augmentation(img_file, json_file, my_augmenter, NUM_AUG, r"E:\OUT/")
  File "e:/2023_Code_WEB/imgAugForLabelmeAnootation-main/poly_aug.py", line 103, in augmentation
    polys_oi = make_polys(json_path)
  File "e:/2023_Code_WEB/imgAugForLabelmeAnootation-main/poly_aug.py", line 30, in make_polys
    with open(json_file, "r") as js:
PermissionError: [Errno 13] Permission denied: 'E:\\JSON'
```

**Comment by MlLearnerAkash** [comment]
Thanks for reaching out .
The error seems to be permission issue with the E:\Img folder in windows. You can find lots of solution on this how to get rid of it.
